using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Workload.TabelWindow;

namespace Workload
{
    public class TableWindowPresentation<T>: TableWindowPresentation<T, T> where T: class
    { public TableWindowPresentation(System.String name, ICreateEditPage createEditPage) : base(name, createEditPage) { } }

    public class TableWindowPresentation<T, U> where T: class where U:class
    {
        public TableWindowPresentation(System.String name, ICreateEditPage createEditPage)
        {
            this.Name = name;
            this.CreateEditPage = createEditPage;
        }

        public void InitPage()
        {
            this.TablePage = new TablePage();
            this.TablePage.CreateEditPanel.Content = this.CreateEditPage;

            try
            {
                if (typeof(U) == typeof(T))
                {
                    MainSet.Load();
                    this.TablePage.tableGrid.ItemsSource = this.MainSet.Local.ToBindingList();
                }
                else
                {
                    this.MainSet.Local.CollectionChanged += new System.Collections.Specialized.NotifyCollectionChangedEventHandler((object obj, System.Collections.Specialized.NotifyCollectionChangedEventArgs args) => this.TablePage.tableGrid.ItemsSource = this.MainSet.Local.Select(n => this.CreateEditPage.ConvertToPresent(n)).AsEnumerable());
                    MainSet.Load();
                }

                this.TablePage.tableGrid.AutoGeneratedColumns += new EventHandler((object obj, EventArgs args) =>
                {
                    foreach (System.Windows.Controls.DataGridColumn column in this.TablePage.tableGrid.Columns)
                    {
                        if (this.CreateEditPage.ColumnsToHide.Any(p => p == (System.String)column.Header)) column.Visibility = System.Windows.Visibility.Hidden;
                        if (this.CreateEditPage.ColumnsNames.ContainsKey((System.String)column.Header)) column.Header = this.CreateEditPage.ColumnsNames[(System.String)column.Header];
                    }
                });

            }
            catch(Exception e)
            { System.Windows.MessageBox.Show(e.Message, "ERROR"); }



            this.TablePage.DelBut.Click += new System.Windows.RoutedEventHandler((object obj, System.Windows.RoutedEventArgs args) =>
            {
                if (this.TablePage.tableGrid.SelectedItem != null) this.Context.Entry<T>(this.MainSet.Single(this.CreateEditPage.GetSingleEntity)).State = EntityState.Deleted;
                this.Context.SaveChanges();
                this.TablePage.tableGrid.Items.Refresh();
            });



            this.TablePage.tableGrid.SelectionChanged +=
                new System.Windows.Controls.SelectionChangedEventHandler((object obj, System.Windows.Controls.SelectionChangedEventArgs args) => 
                {
                    T entity = (T)this.TablePage.tableGrid.SelectedItem;
                    if (entity == null)
                    {
                        this.TablePage.OkBut.IsEnabled = false;
                        this.CreateEditPage.CleanFields();
                        return;
                    }
                    else
                    {
                        this.CreateEditPage.EditedEntity = entity;
                        this.TablePage.OkBut.IsEnabled = this.CreateEditPage.FieldsNotEmpty;
                    }
                });

            this.CreateEditPage.FieldsHasBeenChanged += new FieldsChanged(() => this.TablePage.OkBut.IsEnabled = this.CreateEditPage.FieldsNotEmpty);

            this.TablePage.OkBut.Click += new System.Windows.RoutedEventHandler((object obj, System.Windows.RoutedEventArgs args) =>
            {
                T inEditEntity = this.MainSet.Single(this.CreateEditPage.GetSingleEntity);
                this.Context.Entry(inEditEntity).CurrentValues.SetValues(this.CreateEditPage.EditedEntity);
                this.Context.SaveChanges();
                this.TablePage.tableGrid.Items.Refresh();
            });

            this.TablePage.CompleteCreateBut.Click += new System.Windows.RoutedEventHandler((object obj, System.Windows.RoutedEventArgs args) =>
            {
                if (this.CreateEditPage.FieldsNotEmpty)
                {
                    T toCreate = this.CreateEditPage.EditedEntity;
                    this.CreateEditPage.AssingNewId(ref toCreate, this.MainSet.Count() > 0 ? (this.MainSet.Max(this.CreateEditPage.GetId) + 1) : 0);
                    this.MainSet.Add(toCreate);
                    this.Context.SaveChanges();
                    this.TablePage.tableGrid.Items.Refresh();
                }
            });
        }



        public Entities Context => ((App)System.Windows.Application.Current).DBContext;

        public System.String Name;

        public TablePage TablePage;
        protected DbSet<T> MainSet => this.Context.Set<T>();

        public ICreateEditPage CreateEditPage;

        public delegate void FieldsChanged();
        public interface ICreateEditPage
        {
            void CleanFields();
            T EditedEntity { get; set; }

            U ConvertToPresent(T entity);

            System.Linq.Expressions.Expression<Func<T, bool>> GetSingleEntity { get; }

            System.Linq.Expressions.Expression<Func<T, int>> GetId { get; }

            void AssingNewId(ref T entity, int newId);

            bool FieldsNotEmpty { get; }

            event FieldsChanged FieldsHasBeenChanged;

            System.String[] ColumnsToHide { get; }

            Dictionary<System.String, System.String> ColumnsNames { get; }
        }

    }
}
