//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_PARAMS
    {
        public int IDX { get; set; }
        public Nullable<int> EDUTYPE_ID { get; set; }
        public Nullable<int> EDUFORM_ID { get; set; }
        public short COURSE_NO { get; set; }
        public Nullable<short> SEMESTER_NO { get; set; }
        public string FACULTY { get; set; }
        public string DEPARTMENT { get; set; }
    }
}
