//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETAILS_TBL()
        {
            this.SUBDETAILS_TBL = new HashSet<SUBDETAILS_TBL>();
        }
    
        public int DETAIL_ID { get; set; }
        public int ITEM_ID { get; set; }
        public int WORK_ID { get; set; }
        public decimal HOURS { get; set; }
    
        public virtual MAIN_TBL MAIN_TBL { get; set; }
        public virtual WORKS_TBL WORKS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBDETAILS_TBL> SUBDETAILS_TBL { get; set; }
    }
}
