//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GROUPS_TBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GROUPS_TBL()
        {
            this.SUBDETAILS_TBL = new HashSet<SUBDETAILS_TBL>();
        }
    
        public int GROUP_ID { get; set; }
        public string GROUP_NAME { get; set; }
        public string GROUP_MISC { get; set; }
        public Nullable<int> EDUFORM_ID { get; set; }
        [Range(1, 6, ErrorMessage ="Course can be only in range between 1 and 6.")]
        public short COURSE_NO { get; set; }
        public short BUDGET_CNT { get; set; }
        public short CONTRACT_CNT { get; set; }
        public string FACULTY_ABBR { get; set; }
    
        public virtual EDUFORMS_TBL EDUFORMS_TBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUBDETAILS_TBL> SUBDETAILS_TBL { get; set; }
    }
}
