//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workload
{
    using FirebirdSql.Data.FirebirdClient;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Entities : DbContext
    {
        public Entities(System.String connStr = "name=Entities") : base(connStr) { }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Properties<string>().Configure(x => x.HasColumnType("VARCHAR"));
            modelBuilder.Properties<string>().Configure(x => x.IsUnicode(true));
        }
    
        public virtual DbSet<APP_PARAMS> APP_PARAMS { get; set; }
        public virtual DbSet<DETAILS_TBL> DETAILS_TBL { get; set; }
        public virtual DbSet<EDUFORMS_TBL> EDUFORMS_TBL { get; set; }
        public virtual DbSet<EDUTYPES_TBL> EDUTYPES_TBL { get; set; }
        public virtual DbSet<GROUPS_TBL> GROUPS_TBL { get; set; }
        public virtual DbSet<MAIN_TBL> MAIN_TBL { get; set; }
        public virtual DbSet<SUBDETAILS_TBL> SUBDETAILS_TBL { get; set; }
        public virtual DbSet<SUBJECTS_TBL> SUBJECTS_TBL { get; set; }
        public virtual DbSet<TEACHERS_TBL> TEACHERS_TBL { get; set; }
        public virtual DbSet<WORKS_TBL> WORKS_TBL { get; set; }
    }
}
